<?php 

defined( 'FINCH' ) || die();

function get_finch_pdf_html( $page ){
 	$str = '';
	$str .= '<div id="outerContainer">' . PHP_EOL;
	$str .= '<div id="sidebarContainer">' . PHP_EOL;
	$str .= '<div id="toolbarSidebar">' . PHP_EOL;
	$str .= '<div class="splitToolbarButton toggled">' . PHP_EOL;
	$str .= '<button id="viewThumbnail" class="toolbarButton group toggled" title="Show Thumbnails" tabindex="2" data-l10n-id="thumbs">' . PHP_EOL;
	$str .= '<span data-l10n-id="thumbs_label">Thumbnails</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="viewOutline" class="toolbarButton group" title="Show Document Outline" tabindex="3" data-l10n-id="outline">' . PHP_EOL;
    $str .= '<span data-l10n-id="outline_label">Document Outline</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="viewAttachments" class="toolbarButton group" title="Show Attachments" tabindex="4" data-l10n-id="attachments">' . PHP_EOL;
	$str .= '<span data-l10n-id="attachments_label">Attachments</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="sidebarContent">' . PHP_EOL;
	$str .= '<div id="thumbnailView">' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="outlineView" class="hidden">' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="attachmentsView" class="hidden">' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div><!-- sidebarContainer -->' . PHP_EOL;
    $str .= '<div id="mainContainer">' . PHP_EOL;
	$str .= '<div class="findbar hidden doorHanger hiddenSmallView" id="findbar">' . PHP_EOL;
	$str .= '<label for="findInput" class="toolbarLabel" data-l10n-id="find_label">Find:</label>' . PHP_EOL;
	$str .= '<input id="findInput" class="toolbarField" tabindex="91">' . PHP_EOL;
	$str .= '<div class="splitToolbarButton">' . PHP_EOL;
	$str .= '<button class="toolbarButton findPrevious" title="" id="findPrevious" tabindex="92" data-l10n-id="find_previous">' . PHP_EOL;
	$str .= '<span data-l10n-id="find_previous_label">Previous</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="splitToolbarButtonSeparator"></div>' . PHP_EOL;
	$str .= '<button class="toolbarButton findNext" title="" id="findNext" tabindex="93" data-l10n-id="find_next">' . PHP_EOL;
	$str .= '<span data-l10n-id="find_next_label">Next</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<input type="checkbox" id="findHighlightAll" class="toolbarField" tabindex="94">' . PHP_EOL;
	$str .= '<label for="findHighlightAll" class="toolbarLabel" data-l10n-id="find_highlight">Highlight all</label>' . PHP_EOL;
	$str .= '<input type="checkbox" id="findMatchCase" class="toolbarField" tabindex="95">' . PHP_EOL;
	$str .= '<label for="findMatchCase" class="toolbarLabel" data-l10n-id="find_match_case_label">Match case</label>' . PHP_EOL;
	$str .= '<span id="findResultsCount" class="toolbarLabel hidden"></span>' . PHP_EOL;
	$str .= '<span id="findMsg" class="toolbarLabel"></span>' . PHP_EOL;
	$str .= '</div><!-- findbar -->' . PHP_EOL;  
	$str .= '<div id="secondaryToolbar" class="secondaryToolbar hidden doorHangerRight">' . PHP_EOL;
	$str .= '<div id="secondaryToolbarButtonContainer">' . PHP_EOL;
	$str .= '<button id="secondaryPresentationMode" class="secondaryToolbarButton presentationMode visibleLargeView" title="Switch to Presentation Mode" tabindex="51" data-l10n-id="presentation_mode">' . PHP_EOL;
	$str .= '<span data-l10n-id="presentation_mode_label">Presentation Mode</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="secondaryOpenFile" class="secondaryToolbarButton openFile visibleLargeView" title="Open File" tabindex="52" data-l10n-id="open_file">' . PHP_EOL;
	$str .= '<span data-l10n-id="open_file_label">Open</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="secondaryPrint" class="secondaryToolbarButton print visibleMediumView" title="Print" tabindex="53" data-l10n-id="print">' . PHP_EOL;
	$str .= '<span data-l10n-id="print_label">Print</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="secondaryDownload" class="secondaryToolbarButton download visibleMediumView" title="Download" tabindex="54" data-l10n-id="download">' . PHP_EOL;
	$str .= '<span data-l10n-id="download_label">Download</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<a href="#" id="secondaryViewBookmark" class="secondaryToolbarButton bookmark visibleSmallView" title="Current view (copy or open in new window)" tabindex="55" data-l10n-id="bookmark">' . PHP_EOL;
	$str .= '<span data-l10n-id="bookmark_label">Current View</span>' . PHP_EOL;
	$str .= '</a>' . PHP_EOL;
	$str .= '<div class="horizontalToolbarSeparator visibleLargeView"></div>' . PHP_EOL;
	$str .= '<button id="firstPage" class="secondaryToolbarButton firstPage" title="Go to First Page" tabindex="56" data-l10n-id="first_page">' . PHP_EOL;
	$str .= '<span data-l10n-id="first_page_label">Go to First Page</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="lastPage" class="secondaryToolbarButton lastPage" title="Go to Last Page" tabindex="57" data-l10n-id="last_page">' . PHP_EOL;
	$str .= '<span data-l10n-id="last_page_label">Go to Last Page</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="horizontalToolbarSeparator"></div>' . PHP_EOL;
	$str .= '<button id="pageRotateCw" class="secondaryToolbarButton rotateCw" title="Rotate Clockwise" tabindex="58" data-l10n-id="page_rotate_cw">' . PHP_EOL;
	$str .= '<span data-l10n-id="page_rotate_cw_label">Rotate Clockwise</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="pageRotateCcw" class="secondaryToolbarButton rotateCcw" title="Rotate Counterclockwise" tabindex="59" data-l10n-id="page_rotate_ccw">' . PHP_EOL;
	$str .= '<span data-l10n-id="page_rotate_ccw_label">Rotate Counterclockwise</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="horizontalToolbarSeparator"></div>' . PHP_EOL;
	$str .= '<button id="toggleHandTool" class="secondaryToolbarButton handTool" title="Enable hand tool" tabindex="60" data-l10n-id="hand_tool_enable">' . PHP_EOL;
	$str .= '<span data-l10n-id="hand_tool_enable_label">Enable hand tool</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="horizontalToolbarSeparator"></div>' . PHP_EOL;
	$str .= '<button id="documentProperties" class="secondaryToolbarButton documentProperties" title="Document Properties…" tabindex="61" data-l10n-id="document_properties">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_label">Document Properties…</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div><!-- secondaryToolbar -->' . PHP_EOL;
	$str .= '<div class="toolbar">' . PHP_EOL;
	$str .= '<div id="toolbarContainer">' . PHP_EOL;
	$str .= '<div id="toolbarViewer">' . PHP_EOL;
	$str .= '<div id="toolbarViewerLeft">' . PHP_EOL;
	$str .= '<button id="sidebarToggle" class="toolbarButton" title="Toggle Sidebar" tabindex="11" data-l10n-id="toggle_sidebar">' . PHP_EOL;
	$str .= '<span data-l10n-id="toggle_sidebar_label">Toggle Sidebar</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="toolbarButtonSpacer"></div>' . PHP_EOL;
	$str .= '<button id="viewFind" class="toolbarButton group hiddenSmallView" title="Find in Document" tabindex="12" data-l10n-id="findbar">' . PHP_EOL;
	$str .= '<span data-l10n-id="findbar_label">Find</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="splitToolbarButton">' . PHP_EOL;
	$str .= '<button class="toolbarButton pageUp" title="Previous Page" id="previous" tabindex="13" data-l10n-id="previous">' . PHP_EOL;
	$str .= '<span data-l10n-id="previous_label">Previous</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="splitToolbarButtonSeparator"></div>' . PHP_EOL;
	$str .= '<button class="toolbarButton pageDown" title="Next Page" id="next" tabindex="14" data-l10n-id="next">' . PHP_EOL;
	$str .= '<span data-l10n-id="next_label">Next</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<label id="pageNumberLabel" class="toolbarLabel" for="pageNumber" data-l10n-id="page_label">Page: </label>' . PHP_EOL;
	$str .= '<input type="number" id="pageNumber" class="toolbarField pageNumber" value="1" size="4" min="1" tabindex="15">' . PHP_EOL;
	$str .= '<span id="numPages" class="toolbarLabel"></span>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="toolbarViewerRight">' . PHP_EOL;
	$str .= '<button id="presentationMode" class="toolbarButton presentationMode hiddenLargeView" title="Switch to Presentation Mode" tabindex="31" data-l10n-id="presentation_mode">' . PHP_EOL;
	$str .= '<span data-l10n-id="presentation_mode_label">Presentation Mode</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="openFile" class="toolbarButton openFile hiddenLargeView" title="Open File" tabindex="32" data-l10n-id="open_file">' . PHP_EOL;
	$str .= '<span data-l10n-id="open_file_label">Open</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="print" class="toolbarButton print hiddenMediumView" title="Print" tabindex="33" data-l10n-id="print">' . PHP_EOL;
	$str .= '<span data-l10n-id="print_label">Print</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<button id="download" class="toolbarButton download hiddenMediumView" title="Download" tabindex="34" data-l10n-id="download">' . PHP_EOL;
	$str .= '<span data-l10n-id="download_label">Download</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<a href="#" id="viewBookmark" class="toolbarButton bookmark hiddenSmallView" title="Current view (copy or open in new window)" tabindex="35" data-l10n-id="bookmark">' . PHP_EOL;
	$str .= '<span data-l10n-id="bookmark_label">Current View</span>' . PHP_EOL;
	$str .= '</a>' . PHP_EOL;
	$str .= '<div class="verticalToolbarSeparator hiddenSmallView"></div>' . PHP_EOL;
	$str .= '<button id="secondaryToolbarToggle" class="toolbarButton" title="Tools" tabindex="36" data-l10n-id="tools">' . PHP_EOL;
	$str .= '<span data-l10n-id="tools_label">Tools</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="outerCenter">' . PHP_EOL;
	$str .= '<div class="innerCenter" id="toolbarViewerMiddle">' . PHP_EOL;
	$str .= '<div class="splitToolbarButton">' . PHP_EOL;
	$str .= '<button id="zoomOut" class="toolbarButton zoomOut" title="Zoom Out" tabindex="21" data-l10n-id="zoom_out">' . PHP_EOL;
	$str .= '<span data-l10n-id="zoom_out_label">Zoom Out</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '<div class="splitToolbarButtonSeparator"></div>' . PHP_EOL;
	$str .= '<button id="zoomIn" class="toolbarButton zoomIn" title="Zoom In" tabindex="22" data-l10n-id="zoom_in">' . PHP_EOL;
	$str .= '<span data-l10n-id="zoom_in_label">Zoom In</span>' . PHP_EOL;
	$str .= '</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<span id="scaleSelectContainer" class="dropdownToolbarButton">' . PHP_EOL;
	$str .= '<select id="scaleSelect" title="Zoom" tabindex="23" data-l10n-id="zoom">' . PHP_EOL;
	$str .= '<option id="pageAutoOption" title="" value="auto" selected="selected" data-l10n-id="page_scale_auto">Automatic Zoom</option>' . PHP_EOL;
	$str .= '<option id="pageActualOption" title="" value="page-actual" data-l10n-id="page_scale_actual">Actual Size</option>' . PHP_EOL;
	$str .= '<option id="pageFitOption" title="" value="page-fit" data-l10n-id="page_scale_fit">Fit Page</option>' . PHP_EOL;
	$str .= '<option id="pageWidthOption" title="" value="page-width" data-l10n-id="page_scale_width">Full Width</option>' . PHP_EOL;
	$str .= '<option id="customScaleOption" title="" value="custom"></option>' . PHP_EOL;
	$str .= '<option title="" value="0.5" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 50 }\'>50%</option>' . PHP_EOL;
	$str .= '<option title="" value="0.75" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 75 }\'>75%</option>' . PHP_EOL;
	$str .= '<option title="" value="1" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 100 }\'>100%</option>' . PHP_EOL;
	$str .= '<option title="" value="1.25" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 125 }\'>125%</option>' . PHP_EOL;
	$str .= '<option title="" value="1.5" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 150 }\'>150%</option>' . PHP_EOL;
	$str .= '<option title="" value="2" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 200 }\'>200%</option>' . PHP_EOL;
	$str .= '<option title="" value="3" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 300 }\'>300%</option>' . PHP_EOL;
	$str .= '<option title="" value="4" data-l10n-id="page_scale_percent" data-l10n-args=\'{ "scale": 400 }\'>400%</option>' . PHP_EOL;
	$str .= '</select>' . PHP_EOL;
	$str .= '</span>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="loadingBar">' . PHP_EOL;
	$str .= '<div class="progress">' . PHP_EOL;
	$str .= '<div class="glimmer">' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<menu type="context" id="viewerContextMenu">' . PHP_EOL;
	$str .= '<menuitem id="contextFirstPage" label="First Page" data-l10n-id="first_page"></menuitem>' . PHP_EOL;
	$str .= '<menuitem id="contextLastPage" label="Last Page" data-l10n-id="last_page"></menuitem>' . PHP_EOL;
    $str .= '<menuitem id="contextPageRotateCw" label="Rotate Clockwise" data-l10n-id="page_rotate_cw"></menuitem>' . PHP_EOL;
	$str .= '<menuitem id="contextPageRotateCcw" label="Rotate Counter-Clockwise" data-l10n-id="page_rotate_ccw"></menuitem>' . PHP_EOL;
	$str .= '</menu>' . PHP_EOL;
	$str .= '<div id="viewerContainer" tabindex="0">' . PHP_EOL;
	$str .= '<div id="viewer" class="pdfViewer"></div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="errorWrapper" hidden="true">' . PHP_EOL;
	$str .= '<div id="errorMessageLeft">' . PHP_EOL;
	$str .= '<span id="errorMessage"></span>' . PHP_EOL;
	$str .= '<button id="errorShowMore" data-l10n-id="error_more_info">More Information</button>' . PHP_EOL;
	$str .= '<button id="errorShowLess" data-l10n-id="error_less_info" hidden="true">Less Information</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="errorMessageRight">' . PHP_EOL;
	$str .= '<button id="errorClose" data-l10n-id="error_close">Close</button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="clearBoth"></div>' . PHP_EOL;
	$str .= '<textarea id="errorMoreInfo" hidden="true" readonly="readonly"></textarea>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div><!-- mainContainer -->' . PHP_EOL;
	$str .= '<div id="overlayContainer" class="hidden">' . PHP_EOL;
	$str .= '<div id="passwordOverlay" class="container hidden">' . PHP_EOL;
	$str .= '<div class="dialog">' . PHP_EOL;
    $str .= '<div class="row">' . PHP_EOL;
	$str .= '<p id="passwordText" data-l10n-id="password_label">Enter the password to open this PDF file:</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<input type="password" id="password" class="toolbarField" />' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="buttonRow">' . PHP_EOL;
	$str .= '<button id="passwordCancel" class="overlayButton"><span data-l10n-id="password_cancel">Cancel</span></button>' . PHP_EOL;
	$str .= '<button id="passwordSubmit" class="overlayButton"><span data-l10n-id="password_ok">OK</span></button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div id="documentPropertiesOverlay" class="container hidden">' . PHP_EOL;
	$str .= '<div class="dialog">' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_file_name">File name:</span> <p id="fileNameField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_file_size">File size:</span> <p id="fileSizeField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="separator"></div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_title">Title:</span> <p id="titleField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_author">Author:</span> <p id="authorField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_subject">Subject:</span> <p id="subjectField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_keywords">Keywords:</span> <p id="keywordsField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_creation_date">Creation Date:</span> <p id="creationDateField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_modification_date">Modification Date:</span> <p id="modificationDateField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_creator">Creator:</span> <p id="creatorField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="separator"></div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_producer">PDF Producer:</span> <p id="producerField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_version">PDF Version:</span> <p id="versionField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="row">' . PHP_EOL;
	$str .= '<span data-l10n-id="document_properties_page_count">Page Count:</span> <p id="pageCountField">-</p>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="buttonRow">' . PHP_EOL;
	$str .= '<button id="documentPropertiesClose" class="overlayButton"><span data-l10n-id="document_properties_close">Close</span></button>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div><!-- overlayContainer -->' . PHP_EOL;
	$str .= '</div><!-- outerContainer -->' . PHP_EOL;
	$str .= '<div id="printContainer"></div>' . PHP_EOL;
	$str .= '<div id="mozPrintCallback-shim" class="hidden">' . PHP_EOL;
	$str .= '<div class="mozPrintCallback-dialog-box">Preparing document for printing...' . PHP_EOL;
	$str .= '<div class="progress-row">' . PHP_EOL;
	$str .= '<progress value="0" max="100"></progress>' . PHP_EOL;
	$str .= '<span class="relative-progress">0%</span>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '<div class="progress-actions">' . PHP_EOL;
	$str .= '<input type="button" value="Cancel" class="mozPrintCallback-cancel">' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	$str .= '</div>' . PHP_EOL;
	return $str;
}